### ISSUE TITLE
Draft review - Katy Huff

### ISSUE THREAD

**Issue by smpark7** [arfc/2025-park-mc#2]
The M&C paper draft is ready for review.

Due to the 10-page limit, I cut down the scope to only 1-D models & results. I still need to cut it down by one page. I'm considering removing some of the middle energy group plots in Figures 5 & 6. Please let me know if you have any other suggestions for cutting.

[main.pdf](https://github.com/user-attachments/files/17578805/main.pdf)

**Comment by katyhuff** [comment]
![2024-10-30-park-mc.pdf](https://github.com/user-attachments/files/17581404/2024-10-30-park-mc.pdf)

**Comment by katyhuff** [comment]
![2024-10-30-park-mc.pdf](https://github.com/user-attachments/files/17581424/2024-10-30-park-mc.pdf)

**Comment by smpark7** [comment]
Thank you for the quick turnaround!

**Comment by katyhuff** [comment]
Nice paper -- looks good. Not sure how to shorten. Honestly, maybe it could be split into two papers if they give you a chance with a deadline extension.
