### ISSUE TITLE
Draft review - Madicken Munk

### ISSUE THREAD

**Issue by smpark7** [arfc/2025-park-mc#3]
The M&C paper draft is ready for review.

Due to the 10-page limit, I cut down the scope to only 1-D models & results. I still need to cut it down by one page. I'm considering removing some of the middle energy group plots in Figures 5 & 6. Please let me know if you have any other suggestions for cutting.

[main.pdf](https://github.com/user-attachments/files/17578805/main.pdf)

**Comment by munkm** [comment]
I will do my best to get this to you tomorrow afternoon or early evening.

**Comment by munkm** [comment]
One initial comment I have for you is that you should add a short section explaining how your work is different from other hybrid methods that couple diffusion to transport methods. Your reviewers will bring that up, and I think making it clear will help you in the review process. I know you're over the page limit, but in my experience as long as your main paper body isn't over 10 pages you will be ok.

**Comment by munkm** [comment]
Here are my comments. I agree with @katyhuff that I'm not if there's anywhere appropriate to shorten it. I think you should be ok with this length + my requested changes though. 

[park-25-munk.pdf](https://github.com/user-attachments/files/17604403/park-25-munk.pdf)

**Comment by smpark7** [comment]
Thank you for the thorough review!
